added homekit ID to be displayed with index.html
maximkulkin/esp-wifi-config pull request #17
Opened 2019-09-06 19:44 UTC by stellarshenson

accessory ID can be set in the project (accessory_id_set) and displayed with index.html

I am also generating the accessoryt ID in the main program with the following code:

/**
 * generates accessory ID from the chipID, turns 32 bit chipID into 4-byte chunks and gets modulo 9 from each
 * */
void accessory_id_init() {
    uint32_t chipid = sdk_system_get_chip_id();
    uint8_t accessory_id_digits[] = { chipid >> 0 & 0xf % 9,  chipid >> 4 & 0xf % 9, chipid >> 8 & 0xf % 9, 
    	chipid >> 12 & 0xf % 9, chipid >> 16 & 0xf % 9, chipid >> 20 & 0xf % 9, chipid >> 24 & 0xf % 9, chipid >> 28 & 0xf % 9 }; 
    config.password = (char*) malloc( 11 * sizeof(char));
    snprintf(config.password, 11, "%u%u%u-%u%u-%u%u%u", accessory_id_digits[0], accessory_id_digits[1], accessory_id_digits[2], 
    	                               accessory_id_digits[3], accessory_id_digits[4], accessory_id_digits[5], accessory_id_digits[6], accessory_id_digits[7]);
    
    //set accessory ID to the generated one. This is used in the wifi-config library
    accessory_id_set(config.password);
}

2019-09-06 20:16 UTC, maximkulkin commented
This is a bad way to structure this: the library are not necessarily meant to be used with HomeKit, so adding HomeKit specific configuration/functionality is a bad practice.

What's wrong with current practice of having WiFi AP SSID named after accessory type and ID ?

2019-09-06 21:33 UTC, stellarshenson commented
Hey thanks Maxim,

I wouldn’t argue, i just wanted to have the accessory ID injected in the AP homepage, but maybe something like a “custom html” injected from the main app config would work. 

What do you think? 



- Konrad

On 6 Sep 2019, at 22:16, Maxim Kulkin <notifications@github.com> wrote:

This is a bad way to structure this: the library are not necessarily meant to be used with HomeKit, so adding HomeKit specific configuration/functionality is a bad practice.

What's wrong with current practice of having WiFi AP SSID named after accessory type and ID ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-06 22:51 UTC, maximkulkin commented
I would like first understand the use case. I know that some people would like to add a custom logo to that page and I plan to allow specifying custom CSS (so you can do both logo and color scheme). Would that be enough?

2019-09-07 05:44 UTC, stellarshenson commented
Hello Maxim,

Specifying logo would be one case, definitely. Another one would be to display the accessory password (I’ve called this accessory id in the code that i shared - where i meant the pairing password).

I have made modifications to the coe - and will send over another pull request along with a screenshot

Sent from my iPad

> On 7 Sep 2019, at 00:51, Maxim Kulkin <notifications@github.com> wrote:
> 
> I would like first understand the use case. I know that some people would like to add a custom logo to that page and I plan to allow specifying custom CSS (so you can do both logo and color scheme). Would that be enough?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-10 08:13 UTC, stellarshenson commented
Hi Maxim, I've added 'custom_section_set' and the respective code. Custom section is the HTML code displayed in the header of the index.html that can be injected by the application that uses the library. This way the library can be still app agnostic and homekit agnostic - and the client application can still inject what is needed (i.e. homekit pairing password)

2019-09-10 16:09 UTC, maximkulkin commented
Since you have added a new section, could you facilitate local testing by modifying testing server to allow seeing custom HTML inplace. I think you need to modify [server functions](https://github.com/maximkulkin/esp-wifi-config/blob/master/tools/server.py#L36-L43) to check for an environment variable (e.g. WIFI_CONFIG_CUSTOM_HTML_TEMPLATE) and if it is set, try to open that file and pass contents as `custom_html_section` keyword argument:

```python
def get_custom_html():
    path = os.environ.get('WIFI_CONFIG_CUSTOM_HTML_TEMPLATE')
    if not path or not os.path.exists(path):
        return ''
    with open(path) as f:
        return f.read()

@app.route('/settings', methods=['GET'])
def get_settings():
    return render_template(
        'index.html',
        networks=WIFI_NETWORKS,
        custom_html_section=get_custom_html(),
    )
```

2019-09-10 16:09 UTC, maximkulkin requested changes

2019-09-10 16:09 UTC, maximkulkin commented on content/index.html
> +	<!-- part HTML_SETTINGS_HEADER_CUSTOM_HTML_SECTION -->
Please revert name back to HTML_SETTINGS_HEADER_CUSTOM_SECTION, there is too much of HTML in this name. I think we can tolerate having section variable named `custom_section`.

2019-09-10 16:09 UTC, maximkulkin commented on src/wifi_config.c
> +static char* custom_html_section = NULL;
Please move this into `wifi_config_context_t` structure.

2019-09-10 16:09 UTC, maximkulkin commented on src/wifi_config.c
> +	char* buffer = (char*) calloc( buffer_size, 0 );
It feels dangerous to pass size == 0 to calloc(): the documentation says it might return you something or return NULL. It would be safer to pass either `1` or `sizeof(char)` as a second argument.

2019-09-10 16:09 UTC, maximkulkin commented on src/wifi_config.c
> +    if( custom_html_section != NULL && strlen(custom_html_section) > 0 ) {
Please follow same code formatting style as throughout the rest of the code: no spaces inside parenthesis and space between keyword (e.g. `if` or `while` and parenthesis). Same comment applies to the rest of changes (I won't repeat them for clearness).

2019-09-10 16:09 UTC, maximkulkin commented on src/wifi_config.c
> +    xTaskCreate(http_task, "wifi_config HTTP", 768, NULL, 2, &context->http_task_handle);
Is it really necessary?

2019-09-10 16:09 UTC, maximkulkin commented on include/wifi_config.h
> +void custom_html_section_set(char *param_custom_html_section);
Please change name to follow library's naming convention with public functions having `wifi_config_` prefix. I think `wifi_config_set_custom_html` would be fine. Also, argument name seem to be too long, I think `char *html` would be enough.

2019-09-10 16:09 UTC, maximkulkin commented on src/wifi_config.c
> +    custom_html_section = param_custom_html_section;
After moving variable into wifi_config_context_t, check that `context` is not NULL otherwise print error message and do nothing.

2019-09-10 16:25 UTC, stellarshenson commented
Maxim, I will. Thanks

- Konrad

On 10 Sep 2019, at 18:09, Maxim Kulkin <notifications@github.com> wrote:

@maximkulkin requested changes on this pull request.

In content/index.html:

> @@ -49,6 +49,9 @@
 <body>
     <div class="container">
         <h1>Join WiFi network</h1>
+	<!-- part HTML_SETTINGS_HEADER_CUSTOM_HTML_SECTION -->
Please revert name back to HTML_SETTINGS_HEADER_CUSTOM_SECTION, there is too much of HTML in this name. I think we can tolerate having section variable named custom_section.

In src/wifi_config.c:

> @@ -59,7 +59,7 @@ typedef struct {
 
 
 static wifi_config_context_t *context = NULL;
-
+static char* custom_html_section = NULL;
Please move this into wifi_config_context_t structure.

In src/wifi_config.c:

> @@ -216,8 +216,21 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
+    if( custom_html_section != NULL && strlen(custom_html_section) > 0 ) {
+	uint8_t buffer_size = strlen(html_settings_header_custom_html_section) + strlen(custom_html_section);
+	char* buffer = (char*) calloc( buffer_size, 0 );
It feels dangerous to pass size == 0 to calloc(): the documentation says it might return you something or return NULL. It would be safer to pass either 1 or sizeof(char) as a second argument.

In src/wifi_config.c:

> @@ -216,8 +216,21 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
+    if( custom_html_section != NULL && strlen(custom_html_section) > 0 ) {
Please follow same code formatting style as throughout the rest of the code: no spaces inside parenthesis and space between keyword (e.g. if or while and parenthesis). Same comment applies to the rest of changes (I won't repeat them for clearness).

In src/wifi_config.c:

> @@ -443,7 +456,7 @@ static void http_task(void *arg) {
 
 
 static void http_start() {
-    xTaskCreate(http_task, "wifi_config HTTP", 512, NULL, 2, &context->http_task_handle);
+    xTaskCreate(http_task, "wifi_config HTTP", 768, NULL, 2, &context->http_task_handle);
Is it really necessary?

In include/wifi_config.h:

> @@ -11,3 +11,5 @@ void wifi_config_init2(const char *ssid_prefix, const char *password, void (*on_
 void wifi_config_reset();
 void wifi_config_get(char **ssid, char **password);
 void wifi_config_set(const char *ssid, const char *password);
+
+void custom_html_section_set(char *param_custom_html_section); 
Please change name to follow library's naming convention with public functions having wifi_config_ prefix. I think wifi_config_set_custom_html would be fine. Also, argument name seem to be too long, I think char *html would be enough.

In src/wifi_config.c:

> @@ -793,3 +806,13 @@ void wifi_config_set(const char *ssid, const char *password) {
     sysparam_set_string("wifi_ssid", ssid);
     sysparam_set_string("wifi_password", password);
 }
+
+/**
+ * sets the custom section to use with the AP homepage
+ * */
+void custom_html_section_set(char *param_custom_html_section) {
+    custom_html_section = param_custom_html_section;
After moving variable into wifi_config_context_t, check that context is not NULL otherwise print error message and do nothing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-10 19:16 UTC, stellarshenson commented
I’ve made some changes that you have suggested, i will add more over the next few days and we’ll be done with this

Regarding the stack size for the httpd task - it was a local change that I have reverted in my recent commits.

Thanks

On 10 Sep 2019, at 18:25, Konrad Jelen <konrad.jelen@googlemail.com> wrote:

Maxim, I will. Thanks

- Konrad

On 10 Sep 2019, at 18:09, Maxim Kulkin <notifications@github.com> wrote:

@maximkulkin requested changes on this pull request.

In content/index.html:

> @@ -49,6 +49,9 @@
 <body>
     <div class="container">
         <h1>Join WiFi network</h1>
+	<!-- part HTML_SETTINGS_HEADER_CUSTOM_HTML_SECTION -->
Please revert name back to HTML_SETTINGS_HEADER_CUSTOM_SECTION, there is too much of HTML in this name. I think we can tolerate having section variable named custom_section.

In src/wifi_config.c:

> @@ -59,7 +59,7 @@ typedef struct {
 
 
 static wifi_config_context_t *context = NULL;
-
+static char* custom_html_section = NULL;
Please move this into wifi_config_context_t structure.

In src/wifi_config.c:

> @@ -216,8 +216,21 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
+    if( custom_html_section != NULL && strlen(custom_html_section) > 0 ) {
+	uint8_t buffer_size = strlen(html_settings_header_custom_html_section) + strlen(custom_html_section);
+	char* buffer = (char*) calloc( buffer_size, 0 );
It feels dangerous to pass size == 0 to calloc(): the documentation says it might return you something or return NULL. It would be safer to pass either 1 or sizeof(char) as a second argument.

In src/wifi_config.c:

> @@ -216,8 +216,21 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
+    if( custom_html_section != NULL && strlen(custom_html_section) > 0 ) {
Please follow same code formatting style as throughout the rest of the code: no spaces inside parenthesis and space between keyword (e.g. if or while and parenthesis). Same comment applies to the rest of changes (I won't repeat them for clearness).

In src/wifi_config.c:

> @@ -443,7 +456,7 @@ static void http_task(void *arg) {
 
 
 static void http_start() {
-    xTaskCreate(http_task, "wifi_config HTTP", 512, NULL, 2, &context->http_task_handle);
+    xTaskCreate(http_task, "wifi_config HTTP", 768, NULL, 2, &context->http_task_handle);
Is it really necessary?

In include/wifi_config.h:

> @@ -11,3 +11,5 @@ void wifi_config_init2(const char *ssid_prefix, const char *password, void (*on_
 void wifi_config_reset();
 void wifi_config_get(char **ssid, char **password);
 void wifi_config_set(const char *ssid, const char *password);
+
+void custom_html_section_set(char *param_custom_html_section); 
Please change name to follow library's naming convention with public functions having wifi_config_ prefix. I think wifi_config_set_custom_html would be fine. Also, argument name seem to be too long, I think char *html would be enough.

In src/wifi_config.c:

> @@ -793,3 +806,13 @@ void wifi_config_set(const char *ssid, const char *password) {
     sysparam_set_string("wifi_ssid", ssid);
     sysparam_set_string("wifi_password", password);
 }
+
+/**
+ * sets the custom section to use with the AP homepage
+ * */
+void custom_html_section_set(char *param_custom_html_section) {
+    custom_html_section = param_custom_html_section;
After moving variable into wifi_config_context_t, check that context is not NULL otherwise print error message and do nothing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-10 20:02 UTC, maximkulkin requested changes

2019-09-10 20:02 UTC, maximkulkin commented on src/wifi_config.c
> +    if( context == NULL ) {
This change makes it inconsistent about how correct you want to be: originally the API was designed so that API user is responsible for not calling it twice and thus no checks about prior initialization was made. Now you kind of say that you care and do not want to do double memory allocation (and thus memory leak), but you still allow for memory leaks, because you initialize `ssid_prefix` and `password` without checking if they were already initialized (and thus leaking memory). I think that this change is orthogonal to the change you want to land (support for custom section in HTML), so I recommend just leave it as is.

2019-09-10 20:02 UTC, maximkulkin commented on src/wifi_config.c
> +	context = malloc(sizeof(wifi_config_context_t));
You shouldn't initialize it here, initialized context assumes proper values in other fields, now you're just breaking invariant by allowing existing context with uninitialized fields. The invariant is: if context exists, it is valid. Setting custom HTML after context initialization is fine since if you do not set custom HTML, an empty one will be used (which is perfectly fine).

Just print error to console and do nothing.

2019-09-10 20:02 UTC, maximkulkin commented on content/index.html
> +	<!-- part HTML_SETTINGS_HEADER_SETTINGS -->
Just noticed "setttings header settings" which does not look nice. Let's just call it HTML_SETTINGS_BODY.

2019-09-10 20:14 UTC, stellarshenson commented
Gotcha. There’s two options really - either push custom content to the initialisation function or set it up later (risking race condition where http server is started and serves the request before custom content is set) 

Should I leve the old initialisation style then? Separate variable in the library - and revert the inotialisation changes? I am ok with either

- Konrad

On 10 Sep 2019, at 22:02, Maxim Kulkin <notifications@github.com> wrote:

@maximkulkin requested changes on this pull request.

In src/wifi_config.c:

> @@ -741,8 +753,10 @@ void wifi_config_init(const char *ssid_prefix, const char *password, void (*on_w
         return;
     }
 
-    context = malloc(sizeof(wifi_config_context_t));
-    memset(context, 0, sizeof(*context));
+    if( context == NULL ) {
This change makes it inconsistent about how correct you want to be: originally the API was designed so that API user is responsible for not calling it twice and thus no checks about prior initialization was made. Now you kind of say that you care and do not want to do double memory allocation (and thus memory leak), but you still allow for memory leaks, because you initialize ssid_prefix and password without checking if they were already initialized (and thus leaking memory). I think that this change is orthogonal to the change you want to land (support for custom section in HTML), so I recommend just leave it as is.

In src/wifi_config.c:

> @@ -793,3 +807,20 @@ void wifi_config_set(const char *ssid, const char *password) {
     sysparam_set_string("wifi_ssid", ssid);
     sysparam_set_string("wifi_password", password);
 }
+
+/**
+ * sets the custom section to use with the AP homepage
+ * at this point context may not be initialised yet, 
+ * so initialise if doesn't exist
+ * */
+void custom_section_set(char *custom_section) {
+    if( context == NULL ) {
+	context = malloc(sizeof(wifi_config_context_t));
You shouldn't initialize it here, initialized context assumes proper values in other fields, now you're just breaking invariant by allowing existing context with uninitialized fields. The invariant is: if context exists, it is valid. Setting custom HTML after context initialization is fine since if you do not set custom HTML, an empty one will be used (which is perfectly fine).

Just print error to console and do nothing.

In content/index.html:

> @@ -48,8 +48,11 @@
 </head>
 <body>
     <div class="container">
+       	<!-- part HTML_SETTINGS_HEADER_CUSTOM_SECTION -->
+	{{custom_section}}
+	<!-- part HTML_SETTINGS_HEADER_SETTINGS -->
Just noticed "setttings header settings" which does not look nice. Let's just call it HTML_SETTINGS_BODY.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-10 20:27 UTC, maximkulkin commented
Fair point, although I would prefer not to do it on initialization just because it will create just another initialization function which there are two already (for backward compatibility). Given functionality involves initializing and announcing an access point, I think there is a considerable delay between call to wifi_config_init* and serving clients, so we can not worry about those cases.

So, yes, as I said, just update `wifi_config_set_custom_html()` to check if `context` is initialized and if not just print message to console and return from function.

2019-09-10 21:05 UTC, stellarshenson commented
Fair. I will do this. Thanks maxim

- Konrad

On 10 Sep 2019, at 22:27, Maxim Kulkin <notifications@github.com> wrote:

Fair point, although I would prefer not to do it on initialization just because it will create just another initialization function which there are two already (for backward compatibility). Given functionality involves initializing and announcing an access point, I think there is a considerable delay between call to wifi_config_init* and serving clients, so we can not worry about those cases.

So, yes, as I said, just update wifi_config_set_custom_html() to check if context is initialized and if not just print message to console and return from function.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-11 23:02 UTC, maximkulkin requested changes
I hate to be picky on PR reviews, especially about naming and formatting, especially when I already pointed out the way to do that, but since it touches public API, I can not just let it in and then fix it myself as somebody might already start using this API and fixes will break it.

2019-09-11 23:02 UTC, maximkulkin commented on content/index.html
> +	 <form action="/settings" method="get">
Seems unnecessary white space change

2019-09-11 23:02 UTC, maximkulkin commented on include/wifi_config.h
> +void wifi_config_custom_section_set(char *custom_section);
"section" is a rather vague term and when you look at API it's not immediately obvious that it's about HTML page. It would be better in API to add more hints (while not overloading it with long words) on what this is about.

So, as I suggested earlier, please name it `wifi_config_set_custom_html(char *html)`.

2019-09-11 23:02 UTC, maximkulkin commented on src/wifi_config.c
> +    char *custom_section;
`custom_html`

2019-09-11 23:02 UTC, maximkulkin commented on src/wifi_config.c
> +    //only send custom section if initialised
These Captain Obvious-style comments do not really do anything other than cluttering the code. Please remove.

2019-09-11 23:02 UTC, maximkulkin commented on src/wifi_config.c
> +    if(context->custom_section != NULL && strlen(context->custom_section) > 0) {
In here you do not really care about exact length of custom HTML section, you just want to make sure that it's not NULL and first character is not end of string (zero). Running `strlen()` adds unnecessary computation here.
```c
if (context->custom_html && context->custom_html[0]) {
```

2019-09-11 23:02 UTC, maximkulkin commented on src/wifi_config.c
> +	char* buffer = (char*) calloc( buffer_size, sizeof(char) ); //fill up the buffer with zeros
Please fix formatting. I mentioned this before, but I still see inconsistent formatting with some functions not having spaces inside parenthesis, but others - having extra spaces where they should not be. In some cases there are spaces both after opening parenthesis and before closing, in other cases - space after opening parenthesis, but no space before closing. Please fix style to match existing code.

2019-09-11 23:02 UTC, maximkulkin commented on src/wifi_config.c
> + * sets the custom section to use with the AP homepage
Again, not much value of the comment since function name already says that. Moreover (and here is the problem with code comments in general right there) - it does not match implementation. I think function name is pretty descriptive that it does not need a comment.

2019-09-11 23:02 UTC, maximkulkin commented on src/wifi_config.c
> +    } else context->custom_section = custom_section;
I do not like this style of nested IF statements when logic is pushed down the nesting tree. The rule of thumb is: happy path should be on top level. It makes code easy to read because you do not need to keep in mind all this state of how did you end up in particular code branch.

In this particular case it's very easy to just check a variable, output a message and exit function.
```c
if (context == NULL) {
    ERROR("...");
    return;
}
```
After reading this you can reset your state of what this code does and continue blank slate.
```c
context->custom_html = html;
```
Also, there is something to consider: here you assume ownership is retained by calling code, which might be good in some cases (e.g. static piece of HTML), but in others it's kind of inconvenient to track that. Other functions *e.g. wifi_config_init()) make copies of passed string arguments.

I think static payloads will be more common and thus having this model is still beneficial for embedded environments, but THIS is something that is worth documenting.

2019-09-12 00:33 UTC, stellarshenson commented
Thanks Maxim, I will update and push only when done

- Konrad

On 12 Sep 2019, at 01:02, Maxim Kulkin <notifications@github.com> wrote:

@maximkulkin requested changes on this pull request.

I hate to be picky on PR reviews, especially about naming and formatting, especially when I already pointed out the way to do that, but since it touches public API, I can not just let it in and then fix it myself as somebody might already start using this API and fixes will break it.

In content/index.html:

>          <h1>Join WiFi network</h1>
-        <form action="/settings" method="get">
+	 <form action="/settings" method="get">
Seems unnecessary white space change

In include/wifi_config.h:

> @@ -11,3 +11,5 @@ void wifi_config_init2(const char *ssid_prefix, const char *password, void (*on_
 void wifi_config_reset();
 void wifi_config_get(char **ssid, char **password);
 void wifi_config_set(const char *ssid, const char *password);
+
+void wifi_config_custom_section_set(char *custom_section); 
"section" is a rather vague term and when you look at API it's not immediately obvious that it's about HTML page. It would be better in API to add more hints (while not overloading it with long words) on what this is about.

So, as I suggested earlier, please name it wifi_config_set_custom_html(char *html).

In src/wifi_config.c:

> @@ -48,6 +48,7 @@ typedef enum {
 typedef struct {
     char *ssid_prefix;
     char *password;
+    char *custom_section;
custom_html

In src/wifi_config.c:

> @@ -216,8 +216,20 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
These Captain Obvious-style comments do not really do anything other than cluttering the code. Please remove.

In src/wifi_config.c:

> @@ -216,8 +216,20 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
+    if(context->custom_section != NULL && strlen(context->custom_section) > 0) {
In here you do not really care about exact length of custom HTML section, you just want to make sure that it's not NULL and first character is not end of string (zero). Running strlen() adds unnecessary computation here.

if (context->custom_html && context->custom_html[0]) {
In src/wifi_config.c:

> @@ -216,8 +216,20 @@ static void wifi_config_server_on_settings(client_t *client) {
     client_send(client, http_prologue, sizeof(http_prologue)-1);
     client_send_chunk(client, html_settings_header);
 
-    char buffer[64];
+
+    //only send custom section if initialised
+    if(context->custom_section != NULL && strlen(context->custom_section) > 0) {
+	uint8_t buffer_size = strlen(html_settings_custom_section) + strlen(context->custom_section); //buffer size is the template size + custom section size
+	char* buffer = (char*) calloc( buffer_size, sizeof(char) ); //fill up the buffer with zeros
Please fix formatting. I mentioned this before, but I still see inconsistent formatting with some functions not having spaces inside parenthesis, but others - having extra spaces where they should not be. In some cases there are spaces both after opening parenthesis and before closing, in other cases - space after opening parenthesis, but no space before closing. Please fix style to match existing code.

In src/wifi_config.c:

> @@ -793,3 +805,17 @@ void wifi_config_set(const char *ssid, const char *password) {
     sysparam_set_string("wifi_ssid", ssid);
     sysparam_set_string("wifi_password", password);
 }
+
+/**
+ * sets the custom section to use with the AP homepage
Again, not much value of the comment since function name already says that. Moreover (and here is the problem with code comments in general right there) - it does not match implementation. I think function name is pretty descriptive that it does not need a comment.

In src/wifi_config.c:

> @@ -793,3 +805,17 @@ void wifi_config_set(const char *ssid, const char *password) {
     sysparam_set_string("wifi_ssid", ssid);
     sysparam_set_string("wifi_password", password);
 }
+
+/**
+ * sets the custom section to use with the AP homepage
+ * at this point context may not be initialised yet, 
+ * so initialise if doesn't exist
+ * */
+void wifi_config_custom_section_set(char *custom_section) {
+    if(context == NULL) { 
+	ERROR("cannot set custom html content, wifi configuration not initialised yet"); 
+    } else context->custom_section = custom_section;
I do not like this style of nested IF statements when logic is pushed down the nesting tree. The rule of thumb is: happy path should be on top level. It makes code easy to read because you do not need to keep in mind all this state of how did you end up in particular code branch.

In this particular case it's very easy to just check a variable, output a message and exit function.

if (context == NULL) {
    ERROR("...");
    return;
}
After reading this you can reset your state of what this code does and continue blank slate.

context->custom_html = html;
Also, there is something to consider: here you assume ownership is retained by calling code, which might be good in some cases (e.g. static piece of HTML), but in others it's kind of inconvenient to track that. Other functions *e.g. wifi_config_init()) make copies of passed string arguments.

I think static payloads will be more common and thus having this model is still beneficial for embedded environments, but THIS is something that is worth documenting.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-09-13 19:59 UTC, merged